---
version: "2.0"

services:
  openclaw:
    image: ghcr.io/zjuuu/openclaw-docker:latest
    env:
      - SETUP_PASSWORD=CHANGE_ME
      - OPENCLAW_CONFIG_PATH=/data/.openclaw/openclaw.json
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
        http_options:
          max_body_size: 524288000
          read_timeout: 600000
          send_timeout: 600000
          next_cases:
            - error
            - timeout
          next_tries: 3
          next_timeout: 600000
    params:
      storage:
        data:
          mount: /data
          readOnly: false

profiles:
  compute:
    openclaw:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          - size: 2Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3

  placement:
    akash:
      pricing:
        openclaw:
          denom: uakt
          amount: 1000

deployment:
  openclaw:
    akash:
      profile: openclaw
      count: 1
